Fix ambiguity around ROUTE_ADVERTISEMENT
ietf-wg-masque/draft-ietf-masque-connect-ip pull request #142
Opened 2023-02-28 23:31 UTC by DavidSchinazi

Fixes #136

2023-02-28 23:49 UTC, tfpauly requested changes
I think for some cases this ends up being equivalent — if I have no routes, I can't send, often.

I also don't love this change implying that

2023-02-28 23:49 UTC, tfpauly commented on draft-ietf-masque-connect-ip.md
> +corresponding entries into its routing table.
In many cases, won't this be equivalent? If I don't have a route to send on, I generally won't be able to send.

I also don't love changing the text to imply that a routing table is used by an implementation to provide access to the CONNECT-IP forwarding session. That's sometimes the case, but there are other models (like just having a flow-scoped connection). Elsewhere, we mention routing tables only as examples, not as a normative behavior.

2023-03-01 00:01 UTC, tfpauly commented on draft-ietf-masque-connect-ip.md
> +corresponding entries into its routing table.
```suggestion
Upon receiving the ROUTE_ADVERTISEMENT capsule, an endpoint MAY update its local
state about what its peer is willing to route (subject to local policy), such as by installing
entries in a routing table.
```

2023-03-01 00:02 UTC, DavidSchinazi commented on draft-ietf-masque-connect-ip.md
> +entries in a routing table.
```suggestion
state about what its peer is willing to route (subject to local policy), such
as by installing entries in a routing table.
```

2023-03-01 00:03 UTC, DavidSchinazi commented on draft-ietf-masque-connect-ip.md
> +state about what its peer is willing to route (subject to local policy), such
```suggestion
state regarding what its peer is willing to route (subject to local policy), such
```

2023-03-01 00:08 UTC, tfpauly approved these changes

2023-03-01 00:21 UTC, martinduke approved these changes

2023-03-01 14:23 UTC, gloinul approved these changes

2023-03-01 16:14 UTC, merged